Controllers/BusinessesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Course_end_project2phase_3;
using Course_end_project2phase_3.Models;

namespace Course_end_project2phase_3.Controllers
{
    public class BusinessesController : Controller
    {
        private LaptopsellEntities db = new LaptopsellEntities();

        // GET: Businesses
        public ActionResult Index()
        {
            return View(db.Businesses.ToList());
        }

        // GET: Businesses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Business business = db.Businesses.Find(id);
            if (business == null)
            {
                return HttpNotFound();
            }
            return View(business);
        }

        // GET: Businesses/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Businesses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Description,Price")] Business business)
        {
            if (ModelState.IsValid)
            {
                db.Businesses.Add(business);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(business);
        }

        // GET: Businesses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Business business = db.Businesses.Find(id);
            if (business == null)
            {
                return HttpNotFound();
            }
            return View(business);
        }

        // POST: Businesses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Description,Price")] Business business)
        {
            if (ModelState.IsValid)
            {
                db.Entry(business).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(business);
        }

        // GET: Businesses/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Business business = db.Businesses.Find(id);
            if (business == null)
            {
                return HttpNotFound();
            }
            return View(business);
        }

        // POST: Businesses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Business business = db.Businesses.Find(id);
            db.Businesses.Remove(business);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Course_end_project2phase_3.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/ThinLightsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Course_end_project2phase_3;
using Course_end_project2phase_3.Models;

namespace Course_end_project2phase_3.Controllers
{
    public class ThinLightsController : Controller
    {
        private LaptopsellEntities db = new LaptopsellEntities();

        // GET: ThinLights
        public ActionResult Index()
        {
            return View(db.ThinLights.ToList());
        }

        // GET: ThinLights/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ThinLight thinLight = db.ThinLights.Find(id);
            if (thinLight == null)
            {
                return HttpNotFound();
            }
            return View(thinLight);
        }

        // GET: ThinLights/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ThinLights/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Description,Price")] ThinLight thinLight)
        {
            if (ModelState.IsValid)
            {
                db.ThinLights.Add(thinLight);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(thinLight);
        }

        // GET: ThinLights/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ThinLight thinLight = db.ThinLights.Find(id);
            if (thinLight == null)
            {
                return HttpNotFound();
            }
            return View(thinLight);
        }

        // POST: ThinLights/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Description,Price")] ThinLight thinLight)
        {
            if (ModelState.IsValid)
            {
                db.Entry(thinLight).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(thinLight);
        }

        // GET: ThinLights/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ThinLight thinLight = db.ThinLights.Find(id);
            if (thinLight == null)
            {
                return HttpNotFound();
            }
            return View(thinLight);
        }

        // POST: ThinLights/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ThinLight thinLight = db.ThinLights.Find(id);
            db.ThinLights.Remove(thinLight);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">Laptop Sphere</h1>
        <p class="lead">At Digitals Retailers, we are driven to provide our customers with the best possible deals on all ranges of laptops.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Gaming Laptops</h2>
            <p>
                Level up your gaming experience with our curated selection of high-performance gaming laptops! Dive into immersive graphics, lightning-fast processing, and portable power. Shop now for the ultimate gaming companion and redefine how you play.

            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
            <p>@Html.ActionLink("Business Laptops", "Index", "Businesses", new { area = "" }, new { @class = "btn btn-outline-dark" })</p>

        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Business Laptops</h2>
            <p>Transform your workday with our curated collection of business laptops. Elevate productivity with sleek design, powerful processing, and reliable performance. Shop now for professional-grade laptops that redefine efficiency and style in the business world.</p>

            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
            <p>@Html.ActionLink("Business Laptops", "Index", "Businesses", new { area = "" }, new { @class = "btn btn-outline-dark" })</p>

        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Thin&Light Laptops</h2>
            <p>Discover the perfect blend of power and portability with our selection of thin and light laptops. Streamline your lifestyle with sleek designs, feather-light construction, and impressive performance. Shop now for a laptop that effortlessly combines style and functionality, redefining the way you work and play on the go.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
            <p>@Html.ActionLink("Thin&Light Laptops", "Index", "ThinLights", new { area = "" }, new { @class = "btn btn-outline-dark" })</p>

        </section>
    </div>
</main>